insert into users (name) values
('kyra'),
('patrick'),
('salt'),
('crumple'),
('shodslip'),
('fairyflower'),
('honest a'),
('Esq.');

insert into posts (author, text, hue) values
(2, "capering cod in the river by the copse", 0),
(1, "my  post!!!!", 10),
(1, "i've since calmed down.", 15),
(3, "i woke up today to a big big noise.", 20),
(4, "what kind of person are you? my favorite books are: rainbow magic series; moby dick; harold and the purple crayon; all of shakespeare's works; 1989 by taylor swift; 1984 by that guy; my diary from ages 8-10; my diary from ages 12-14; not my diary from age 11; little women.", 30),
(1, "flip flops flip flop", 35),
(3, "What a lark! What a plunge! For so it had always seemed to her, when, with a little squeak of the hinges, which she could hear now, she had burst open the French windows and plunged at Bourton into the open air. How fresh, how calm, stiller than this of course, the air was in the early morning; like the flap of a wave; the kiss of a wave; chill and sharp and yet (for a girl of eighteen as she then was) solemn, feeling as she did, standing there at the open window, that something awful was about to happen; looking at the flowers, at the trees with the smoke winding off them and the rooks rising, falling; standing and looking until Peter Walsh said, 'Musing among the vegetables?'-was that it?-'I prefer men to cauliflowers'-was that it? He must have said it at breakfast one morning when she had gone out on to the terrace-Peter Walsh. He would be back from India one o£ these days, June or July, she forgot which, for his letters were awfully dull; it was his sayings one remembered; his eyes, his pocket-knife, his smile, his grumpiness and, when millions of things had utterly vanished-how strange it was!-a few sayings like this about cabbages.", 40),
(5, "tpo typo... the poeple on my email chain just don't understand my lyrical lexical perplexical thinking. :(", 45),
(2, "when and where and why and how", 50),
(6, "Does anyone have any advice for fully grown puppies?", 55),
(6, "What would you do if your 53 month old puppy made a certain face at you? I'm thinking about this at work and I don't know :(", 60),
(3, "this is great graphic design", 64),
(7, "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal. Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper that we should do this. But, in a larger sense, we can not dedicate -- we can not consecrate -- we can not hallow -- this ground. The brave men, living and dead, who struggled here, have consecrated it, far above our poor power to add or detract. The world will little note, nor long remember what we say here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here have thus far so nobly advanced. It is rather for us to be here dedicated to the great task remaining before us -- that from these honored dead we take increased devotion to that cause for which they gave the last full measure of devotion -- that we here highly resolve that these dead shall not have died in vain -- that this nation, under God, shall have a new birth of freedom -- and that government of the people, by the people, for the people, shall not perish from the earth.", 70),
(1, "wow", 80),
(2, "-_-", 90),
(3, "ploplopl", 100),
(4, "werstwhile", 110),
(1, "sulfur.....", 120),
(2, "love of life is life itself", 130),
(3, "the essence of the thing is the thing essentially", 140),
(4, "see you lations allegations", 150),
(1, "friendly fire: hi!!! im fire", 160),
(8, "What is all this?", 170),
(3, "lemony cricket", 180),
(4, "halderbash", 190),
(1, "undylatmylating", 200),
(2, "qwergy. qwergy. i think my keyboard is all wronged up", 210),
(3, "shocking new revelations.", 220),
(4, "hahahah! hahahahahahahahah!", 230),
(1, "nothing is going on right now", 240),
(3, "world developments", 250),
(2, "wok a flock a flame", 260),
(4, "all of my friends occupy this isthmus", 270),
(3, "virginia rocks!!!!!!!!!!!!", 280),
(2, "?", 290),
(1, "bunjopalid is cool", 300),
(3, "salt sucks", 310),
(2, "pepa is the besttttt", 320),
(1, "thank you", 330),
(4, "goodbye", 340),
(1, "hello", 350);
